name: 'pr-description-enforcer'
description: 'github action for enforcing description on PR'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
    
runs:
  using: 'node12'
  main: 'dist/index.js'
